## **Mini Project #2: Filtering dataset using pandas.DataFrame.loc and pandas.DataFrame.iloc**


---

This mini-project I built will use [**pandas.DataFrame.loc**](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.loc.html) and [**pandas.DataFrame.iloc**](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.iloc.html) to perform filtering and other necessary data manipulation task using [**Pandas**](https://pandas.pydata.org/pandas-docs/stable/index.html) of [**Python**](https://www.python.org/) Programming Language. This is essential because I want to test my skill if I already know the concept enough and I want to test it with a real world dataset specifically [**Trending Youtube Video Statistics**](https://www.kaggle.com/datasets/datasnaek/youtube-new?select=USvideos.csv) from [**Kaggle**](https://www.kaggle.com/).

### **1. Loading dataset**

Load the dataset using **Pandas** library of **Python** and setup the environment to disable scientific notations and use `IPython` library to produce clean output of every code cell.

In [55]:
import pandas as pd
from IPython.display import display

pd.set_option("display.float_format", "{:.2f}".format) # Disable scientific notations

USvideos = pd.read_csv("../datasets/USvideos.csv")

### **2. Quick Overview**

Get the conscise summary of the dataset's structure and descriptive statistics of the dataset using `.info()` and `.describe()` respectively.

In [56]:
print("Dataset overview:")
display(USvideos.info())

Dataset overview:
<class 'pandas.DataFrame'>
RangeIndex: 40949 entries, 0 to 40948
Data columns (total 16 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   video_id                40949 non-null  str
 1   trending_date           40949 non-null  str
 2   title                   40949 non-null  str
 3   channel_title           40949 non-null  str
 4   category_id             40949 non-null  int64
 5   publish_time            40949 non-null  str
 6   tags                    40949 non-null  str
 7   views                   40949 non-null  int64
 8   likes                   40949 non-null  int64
 9   dislikes                40949 non-null  int64
 10  comment_count           40949 non-null  int64
 11  thumbnail_link          40949 non-null  str
 12  comments_disabled       40949 non-null  bool
 13  ratings_disabled        40949 non-null  bool
 14  video_error_or_removed  40949 non-null  bool
 15  description             40379 non-null  str
dtypes: bool(3), int64(5), str(8)
memory usage: 4.2 MB

None

In [57]:
display(USvideos[["views", "likes", "dislikes", "comment_count"]].describe())

             views      likes   dislikes  comment_count
count     40949.00   40949.00   40949.00       40949.00
mean    2360784.64   74266.70    3711.40        8446.80
std     7394113.76  228885.34   29029.71       37430.49
min         549.00       0.00       0.00           0.00
25%      242329.00    5424.00     202.00         614.00
50%      681861.00   18091.00     631.00        1856.00
75%     1823157.00   55417.00    1938.00        5755.00
max   225211923.00 5613827.00 1674420.00     1361580.00

Get the dataset shape using `.shape` attribute.

In [58]:
display(f"The number of rows and columns: {USvideos.shape}")

'The number of rows and columns: (40949, 16)'

Check what column or variable consist of **missing values** using `.isnull()` and combine by `.sum()` method to get the total number.

In [59]:
columns = USvideos.columns

for column in columns:
    no_of_missing_values = USvideos[column].isnull().sum()

    if no_of_missing_values > 0:
        display(f"Column: `{column}`")
        display(f"Number of missing values: {no_of_missing_values}")

'Column: `description`'

'Number of missing values: 570'

Check the number of unique values for all columns with non-numeric values.

In [60]:
columns = [
    "video_id",
    "trending_date",
    "title",
    "channel_title",
    "publish_time",
    "tags",
    "description"
]

for column in columns:
    no_of_unique_values = len(USvideos[column].dropna().unique())
    display(f"Number of unique values of the column `{column}`: {no_of_unique_values}")

'Number of unique values of the column `video_id`: 6351'

'Number of unique values of the column `trending_date`: 205'

'Number of unique values of the column `title`: 6455'

'Number of unique values of the column `channel_title`: 2207'

'Number of unique values of the column `publish_time`: 6269'

'Number of unique values of the column `tags`: 6055'

'Number of unique values of the column `description`: 6901'

Check the unique values of some columns.

In [61]:
for column in columns:
    unique_values = USvideos[column].dropna().unique()

    if column == "tags":
        unique_values = unique_values[:3]

    else:
        unique_values = unique_values[:5]
    
    display(f"Some unique values of column `{column}`:")
    display(unique_values)

'Some unique values of column `video_id`:'

<StringArray>
['2kyS6SvSYSE', '1ZAPwfrtAFY', '5qpjK5DgCt4', 'puqaWrEC7tY', 'd380meD0W0M']
Length: 5, dtype: str

'Some unique values of column `trending_date`:'

<StringArray>
['17.14.11', '17.15.11', '17.16.11', '17.17.11', '17.18.11']
Length: 5, dtype: str

'Some unique values of column `title`:'

<StringArray>
[                            'WE WANT TO TALK ABOUT OUR MARRIAGE',
 'The Trump Presidency: Last Week Tonight with John Oliver (HBO)',
          'Racist Superman | Rudy Mancuso, King Bach & Lele Pons',
                               'Nickelback Lyrics: Real or Fake?',
                                       'I Dare You: GOING BALD!?']
Length: 5, dtype: str

'Some unique values of column `channel_title`:'

<StringArray>
[         'CaseyNeistat',       'LastWeekTonight',          'Rudy Mancuso',
 'Good Mythical Morning',              'nigahiga']
Length: 5, dtype: str

'Some unique values of column `publish_time`:'

<StringArray>
['2017-11-13T17:13:01.000Z', '2017-11-13T07:30:00.000Z',
 '2017-11-12T19:05:24.000Z', '2017-11-13T11:00:04.000Z',
 '2017-11-12T18:01:41.000Z']
Length: 5, dtype: str

'Some unique values of column `tags`:'

<StringArray>
[                                                                                                                                                                                                                                                                                                           'SHANtell martin',
                                                                                                                                                                                                                     'last week tonight trump presidency|"last week tonight donald trump"|"john oliver trump"|"donald trump"',
 'racist superman|"rudy"|"mancuso"|"king"|"bach"|"racist"|"superman"|"love"|"rudy mancuso poo bear black white official music video"|"iphone x by pineapple"|"lelepons"|"hannahstocking"|"rudymancuso"|"inanna"|"anwar"|"sarkis"|"shots"|"shotsstudios"|"alesso"|"anitta"|"brazil"|"Getting My Driver's License | Lele Pons"']
Length: 3, dtype: str

'Some unique values of column `description`:'

<StringArray>
['SHANTELL'S CHANNEL - https://www.youtube.com/shantellmartin\nCANDICE - https://www.lovebilly.com\n\nfilmed this video in 4k on this -- http://amzn.to/2sTDnRZ\nwith this lens -- http://amzn.to/2rUJOmD\nbig drone - http://tinyurl.com/h4ft3oy\nOTHER GEAR ---  http://amzn.to/2o3GLX5\nSony CAMERA http://amzn.to/2nOBmnv\nOLD CAMERA; http://amzn.to/2o2cQBT\nMAIN LENS; http://amzn.to/2od5gBJ\nBIG SONY CAMERA; http://amzn.to/2nrdJRO\nBIG Canon CAMERA; http://tinyurl.com/jn4q4vz\nBENDY TRIPOD THING; http://tinyurl.com/gw3ylz2\nYOU NEED THIS FOR THE BENDY TRIPOD; http://tinyurl.com/j8mzzua\nWIDE LENS; http://tinyurl.com/jkfcm8t\nMORE EXPENSIVE WIDE LENS; http://tinyurl.com/zrdgtou\nSMALL CAMERA; http://tinyurl.com/hrrzhor\nMICROPHONE; http://tinyurl.com/zefm4jy\nOTHER MICROPHONE; http://tinyurl.com/jxgpj86\nOLD DRONE (cheaper but still great);http://tinyurl.com/zcfmnmd\n\nfollow me; on http://instagram.com/caseyneistat\non https://www.facebook.com/cneistat\non https://twitter.com/CaseyNeistat\n\namazing intro song by https://soundcloud.com/discoteeth\n\nad disclosure.  THIS IS NOT AN AD.  not selling or promoting anything.  but samsung did produce the Shantell Video as a 'GALAXY PROJECT' which is an initiative that enables creators like Shantell and me to make projects we might otherwise not have the opportunity to make.  hope that's clear.  if not ask in the comments and i'll answer any specifics.',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             'One year after the presidential election, John Oliver discusses what we've learned so far and enlists our catheter cowboy to teach Donald Trump what he hasn't.\n\nConnect with Last Week Tonight online...\n\nSubscribe to the Last Week Tonight YouTube channel for more almost news as it almost happens: www.youtube.com/user/LastWeekTonight\n\nFind Last Week Tonight on Facebook like your mom would: http://Facebook.com/LastWeekTonight\n\nFollow us on Twitter for news about jokes and jokes about news: http://Twitter.com/LastWeekTonight\n\nVisit our official site for all that other stuff at once: http://www.hbo.com/lastweektonight',
                                                                                                                                                                                                                                          'WATCH MY PREVIOUS VIDEO ▶ \n\nSUBSCRIBE ► https://www.youtube.com/channel/UC5jkXpfnBhlDjqh0ir5FsIQ?sub_confirmation=1\n\nTHANKS FOR WATCHING! LIKE & SUBSCRIBE FOR MORE VIDEOS!\n-----------------------------------------------------------\nFIND ME ON: \nInstagram | http://instagram.com/rudymancuso\nTwitter | http://twitter.com/rudymancuso\nFacebook | http://facebook.com/rudymancuso\n\nCAST: \nRudy Mancuso | http://youtube.com/c/rudymancuso\nLele Pons | http://youtube.com/c/lelepons\nKing Bach | https://youtube.com/user/BachelorsPadTv\n\nVideo Effects: \nCaleb Natale | https://instagram.com/calebnatale\n\nPA:\nPaulina Gregory\n\n\nShots Studios Channels:\nAlesso | https://youtube.com/c/alesso\nAnitta | http://youtube.com/c/anitta\nAnwar Jibawi | http://youtube.com/c/anwar\nAwkward Puppets | http://youtube.com/c/awkwardpuppets\nHannah Stocking | http://youtube.com/c/hannahstocking\nInanna Sarkis | http://youtube.com/c/inanna\nLele Pons | http://youtube.com/c/lelepons\nMaejor | http://youtube.com/c/maejor\nMike Tyson | http://youtube.com/c/miketyson \nRudy Mancuso | http://youtube.com/c/rudymancuso\nShots Studios | http://youtube.com/c/shots\n\n#Rudy\n#RudyMancuso',
        'Today we find out if Link is a Nickelback amateur or a secret Nickelback devotee. GMM #1218\nDon't miss an all new Ear Biscuits: https://goo.gl/xeZNQt\nWatch Part 4: https://youtu.be/MhCdiiB8CQg | Watch Part 2: https://youtu.be/7qiOrNao9fg\nWatch today's episode from the start: http://bit.ly/GMM1218\n\nPick up all of the official GMM merch only at https://mythical.store\n\nFollow Rhett & Link: \nInstagram: https://instagram.com/rhettandlink\nFacebook: https://facebook.com/rhettandlink\nTwitter: https://twitter.com/rhettandlink\nTumblr: https://rhettandlink.tumblr.com\nSnapchat: @realrhettlink\nWebsite: https://mythical.co/\n\nCheck Out Our Other Mythical Channels:\nGood Mythical MORE: https://youtube.com/goodmythicalmore\nRhett & Link: https://youtube.com/rhettandlink\nThis Is Mythical: https://youtube.com/thisismythical\nEar Biscuits: https://applepodcasts.com/earbiscuits\n\nWant to send us something? https://mythical.co/contact\nHave you made a Wheel of Mythicality intro video? Submit it here: https://bit.ly/GMMWheelIntro\n\nIntro Animation by Digital Twigs: https://www.digitaltwigs.com\nIntro & Outro Music by Jeff Zeigler & Sarah Schimeneck https://www.jeffzeigler.com\nWheel of Mythicality theme: https://www.royaltyfreemusiclibrary.com/\nAll Supplemental Music fromOpus 1 Music: https://opus1.sourceaudio.com/\nWe use ‘The Mouse’ by Blue Microphones https://www.bluemic.com/mouse/',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       'I know it's been a while since we did this show, but we're back with what might be the best episode yet!\nLeave your dares in the comment section! \n\nOrder my book how to write good \nhttp://higatv.com/ryan-higas-how-to-write-good-pre-order-links/\n\nJust Launched New Official Store\nhttps://www.gianthugs.com/collections/ryan\n\nHigaTV Channel\nhttp://www.youtube.com/higatv\n\nTwitter\nhttp://www.twitter.com/therealryanhiga\n\nFacebook\nhttp://www.facebook.com/higatv\n\nWebsite\nhttp://www.higatv.com\n\nInstagram\nhttp://www.instagram.com/notryanhiga\n\nSend us mail or whatever you want here!\nPO Box 232355\nLas Vegas, NV 89105']
Length: 5, dtype: str

Check the number of unique values for some columns.

### **3. Data Cleaning**

Now that we have the overview of what's inside the dataset such as the number of rows and columns, the number of missing values for all columns, unique values per column, and statistical description of the dataset. We will now proceed to clean the dataset based on what we've observed earlier on.

In [62]:
# Handle the missing values of the `description` column
USvideos["description"] = USvideos["description"].fillna("No description")

# Standardize the datatype of `trending_date` and `publish_time` columns
USvideos["trending_date"] = pd.to_datetime(USvideos["trending_date"], format="%y.%d.%m")
USvideos["publish_time"] = pd.to_datetime(USvideos["publish_time"], format="%Y-%m-%dT%H:%M:%S.%fZ")

# Remove unnecessary characters to the `tags` column
USvideos["tags"] = USvideos["tags"].str.replace("[none]", "No tags")
USvideos["tags"] = USvideos["tags"].str.replace("\"", "")
USvideos["tags"] = str(USvideos["tags"].str.split("|").str.join(", "))

### **4. Data Analysis**

After performing **data cleaning**, we can now proceed to analyze and gain insights by performing data filtering using [**pandas.DataFrame.loc**](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.loc.html) and [**pandas.DataFrame.iloc**](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.iloc.html) to the dataset.

Get the row with the index label of `21` from the dataset.

In [63]:
display(USvideos.loc[21]) # Index label 21

video_id                                                        6VhU_T463sU
trending_date                                           2017-11-14 00:00:00
title                     The Making of Hela's Headdress from Thor: Ragn...
channel_title                                                        Tested
category_id                                                              28
publish_time                                            2017-11-12 15:00:01
tags                      0                                          SHA...
views                                                                224019
likes                                                                  3585
dislikes                                                                138
comment_count                                                           208
thumbnail_link               https://i.ytimg.com/vi/6VhU_T463sU/default.jpg
comments_disabled                                                     False
ratings_disabled                                                      False
video_error_or_removed                                                False
description               At this year's DesignerCon, we meet up with Ir...
Name: 21, dtype: object

Get a group of rows starting from the index label `3` to `5` using index label slicing.

In [64]:
display(USvideos.loc[3: 5]) # Index label 3 to 5.

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description
3,puqaWrEC7tY,2017-11-14,Nickelback Lyrics: Real or Fake?,Good Mythical Morning,24,2017-11-13 11:00:04,0 SHA...,343168,10172,666,2146,https://i.ytimg.com/vi/puqaWrEC7tY/default.jpg,False,False,False,Today we find out if Link is a Nickelback amat...
4,d380meD0W0M,2017-11-14,I Dare You: GOING BALD!?,nigahiga,24,2017-11-12 18:01:41,0 SHA...,2095731,132235,1989,17518,https://i.ytimg.com/vi/d380meD0W0M/default.jpg,False,False,False,I know it's been a while since we did this sho...
5,gHZ1Qz0KiKM,2017-11-14,2 Weeks with iPhone X,iJustine,28,2017-11-13 19:07:23,0 SHA...,119180,9763,511,1434,https://i.ytimg.com/vi/gHZ1Qz0KiKM/default.jpg,False,False,False,Using the iPhone for the past two weeks -- her...

Get all the rows with an index label of `2`, `4`, `6`, `8`, and `10`.

In [65]:
display(USvideos.loc[[2, 4, 6, 8, 10]])# Index label of 2, 4, 6, 8, 10.

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description
2,5qpjK5DgCt4,2017-11-14,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23,2017-11-12 19:05:24,0 SHA...,3191434,146033,5339,8181,https://i.ytimg.com/vi/5qpjK5DgCt4/default.jpg,False,False,False,WATCH MY PREVIOUS VIDEO ▶ \n\nSUBSCRIBE ► http...
4,d380meD0W0M,2017-11-14,I Dare You: GOING BALD!?,nigahiga,24,2017-11-12 18:01:41,0 SHA...,2095731,132235,1989,17518,https://i.ytimg.com/vi/d380meD0W0M/default.jpg,False,False,False,I know it's been a while since we did this sho...
6,39idVpFF7NQ,2017-11-14,Roy Moore & Jeff Sessions Cold Open - SNL,Saturday Night Live,24,2017-11-12 05:37:17,0 SHA...,2103417,15993,2445,1970,https://i.ytimg.com/vi/39idVpFF7NQ/default.jpg,False,False,False,Embattled Alabama Senate candidate Roy Moore (...
8,jr9QtXwC9vc,2017-11-14,The Greatest Showman | Official Trailer 2 [HD]...,20th Century Fox,1,2017-11-13 14:00:23,0 SHA...,826059,3543,119,340,https://i.ytimg.com/vi/jr9QtXwC9vc/default.jpg,False,False,False,"Inspired by the imagination of P.T. Barnum, Th..."
10,9wRQljFNDW8,2017-11-14,Dion Lewis' 103-Yd Kick Return TD vs. Denver! ...,NFL,17,2017-11-13 02:05:26,0 SHA...,81377,655,25,177,https://i.ytimg.com/vi/9wRQljFNDW8/default.jpg,False,False,False,New England Patriots returner Dion Lewis blast...

Get all the rows with `views` greater than or equal to **1,000,000** views using boolean masking.

In [66]:
high_viewed_USvideos = USvideos.loc[USvideos["views"] >= 1000000] # Perform boolean masking
display(high_viewed_USvideos)

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description
1,1ZAPwfrtAFY,2017-11-14,The Trump Presidency: Last Week Tonight with J...,LastWeekTonight,24,2017-11-13 07:30:00,0 SHA...,2418783,97185,6146,12703,https://i.ytimg.com/vi/1ZAPwfrtAFY/default.jpg,False,False,False,"One year after the presidential election, John..."
2,5qpjK5DgCt4,2017-11-14,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23,2017-11-12 19:05:24,0 SHA...,3191434,146033,5339,8181,https://i.ytimg.com/vi/5qpjK5DgCt4/default.jpg,False,False,False,WATCH MY PREVIOUS VIDEO ▶ \n\nSUBSCRIBE ► http...
4,d380meD0W0M,2017-11-14,I Dare You: GOING BALD!?,nigahiga,24,2017-11-12 18:01:41,0 SHA...,2095731,132235,1989,17518,https://i.ytimg.com/vi/d380meD0W0M/default.jpg,False,False,False,I know it's been a while since we did this sho...
6,39idVpFF7NQ,2017-11-14,Roy Moore & Jeff Sessions Cold Open - SNL,Saturday Night Live,24,2017-11-12 05:37:17,0 SHA...,2103417,15993,2445,1970,https://i.ytimg.com/vi/39idVpFF7NQ/default.jpg,False,False,False,Embattled Alabama Senate candidate Roy Moore (...
32,n1WpP7iowLc,2017-11-14,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10 17:00:03,0 SHA...,17158531,787419,43420,125882,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40944,BZt0qjTWNhw,2018-06-14,The Cat Who Caught the Laser,AaronsAnimals,15,2018-05-18 13:00:04,0 SHA...,1685609,38160,1385,2657,https://i.ytimg.com/vi/BZt0qjTWNhw/default.jpg,False,False,False,The Cat Who Caught the Laser - Aaron's Animals
40945,1h7KV2sjUWY,2018-06-14,True Facts : Ant Mutualism,zefrank1,22,2018-05-18 01:00:06,0 SHA...,1064798,60008,382,3936,https://i.ytimg.com/vi/1h7KV2sjUWY/default.jpg,False,False,False,No description
40946,D6Oy4LfoqsU,2018-06-14,I GAVE SAFIYA NYGAARD A PERFECT HAIR MAKEOVER ...,Brad Mondo,24,2018-05-18 17:34:22,0 SHA...,1066451,48068,1032,3992,https://i.ytimg.com/vi/D6Oy4LfoqsU/default.jpg,False,False,False,I had so much fun transforming Safiyas hair in...
40947,oV0zkMe1K8s,2018-06-14,How Black Panther Should Have Ended,How It Should Have Ended,1,2018-05-17 17:00:04,0 SHA...,5660813,192957,2846,13088,https://i.ytimg.com/vi/oV0zkMe1K8s/default.jpg,False,False,False,How Black Panther Should Have EndedWatch More ...
40948,ooyjaVdt-jA,2018-06-14,Official Call of Duty®: Black Ops 4 — Multipla...,Call of Duty,20,2018-05-17 17:09:38,0 SHA...,10306119,357079,212976,144795,https://i.ytimg.com/vi/ooyjaVdt-jA/default.jpg,False,False,False,Call of Duty: Black Ops 4 Multiplayer raises t...

In [67]:
top_10_highest_viewed_USvideos = high_viewed_USvideos.sort_values(by="views", ascending=False)[:10]
display(top_10_highest_viewed_USvideos)

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description
38547,VYOjWnS4cMY,2018-06-02,Childish Gambino - This Is America (Official V...,ChildishGambinoVEVO,10,2018-05-06 04:00:07,0 SHA...,225211923,5023450,343541,517232,https://i.ytimg.com/vi/VYOjWnS4cMY/default.jpg,False,False,False,“This is America” by Childish Gambino http://s...
38345,VYOjWnS4cMY,2018-06-01,Childish Gambino - This Is America (Official V...,ChildishGambinoVEVO,10,2018-05-06 04:00:07,0 SHA...,220490543,4962403,338105,512337,https://i.ytimg.com/vi/VYOjWnS4cMY/default.jpg,False,False,False,“This is America” by Childish Gambino http://s...
38146,VYOjWnS4cMY,2018-05-31,Childish Gambino - This Is America (Official V...,ChildishGambinoVEVO,10,2018-05-06 04:00:07,0 SHA...,217750076,4934188,335462,509799,https://i.ytimg.com/vi/VYOjWnS4cMY/default.jpg,False,False,False,“This is America” by Childish Gambino http://s...
37935,VYOjWnS4cMY,2018-05-30,Childish Gambino - This Is America (Official V...,ChildishGambinoVEVO,10,2018-05-06 04:00:07,0 SHA...,210338856,4836448,326902,501722,https://i.ytimg.com/vi/VYOjWnS4cMY/default.jpg,False,False,False,“This is America” by Childish Gambino http://s...
37730,VYOjWnS4cMY,2018-05-29,Childish Gambino - This Is America (Official V...,ChildishGambinoVEVO,10,2018-05-06 04:00:07,0 SHA...,205643016,4776680,321493,496211,https://i.ytimg.com/vi/VYOjWnS4cMY/default.jpg,False,False,False,“This is America” by Childish Gambino http://s...
37531,VYOjWnS4cMY,2018-05-28,Childish Gambino - This Is America (Official V...,ChildishGambinoVEVO,10,2018-05-06 04:00:07,0 SHA...,200820941,4714942,316129,491005,https://i.ytimg.com/vi/VYOjWnS4cMY/default.jpg,False,False,False,“This is America” by Childish Gambino http://s...
37333,VYOjWnS4cMY,2018-05-27,Childish Gambino - This Is America (Official V...,ChildishGambinoVEVO,10,2018-05-06 04:00:07,0 SHA...,196222618,4656929,311042,485797,https://i.ytimg.com/vi/VYOjWnS4cMY/default.jpg,False,False,False,“This is America” by Childish Gambino http://s...
37123,VYOjWnS4cMY,2018-05-26,Childish Gambino - This Is America (Official V...,ChildishGambinoVEVO,10,2018-05-06 04:00:07,0 SHA...,190950401,4594931,305435,479917,https://i.ytimg.com/vi/VYOjWnS4cMY/default.jpg,False,False,False,“This is America” by Childish Gambino http://s...
36913,VYOjWnS4cMY,2018-05-25,Childish Gambino - This Is America (Official V...,ChildishGambinoVEVO,10,2018-05-06 04:00:07,0 SHA...,184446490,4512326,298157,473039,https://i.ytimg.com/vi/VYOjWnS4cMY/default.jpg,False,False,False,“This is America” by Childish Gambino http://s...
36710,VYOjWnS4cMY,2018-05-24,Childish Gambino - This Is America (Official V...,ChildishGambinoVEVO,10,2018-05-06 04:00:07,0 SHA...,179045286,4437175,291098,466470,https://i.ytimg.com/vi/VYOjWnS4cMY/default.jpg,False,False,False,“This is America” by Childish Gambino http://s...