## **Mini Project #2: Filtering dataset using pandas.DataFrame.loc and pandas.DataFrame.iloc**


---

This mini-project I built will use [**pandas.DataFrame.loc**](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.loc.html) and [**pandas.DataFrame.iloc**](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.iloc.html) to perform filtering and other necessary data manipulation task using [**Pandas**](https://pandas.pydata.org/pandas-docs/stable/index.html) of [**Python**](https://www.python.org/) Programming Language. This is essential because I want to test my skill if I already know the concept enough and I want to test it with a real world dataset specifically [**Trending Youtube Video Statistics**](https://www.kaggle.com/datasets/datasnaek/youtube-new?select=USvideos.csv) from [**Kaggle**](https://www.kaggle.com/).

### **1. Loading dataset**

Load the dataset using **Pandas** library of **Python** and setup the environment to disable scientific notations and use `IPython` library to produce clean output of every code cell.

In [63]:
import pandas as pd
from IPython.display import display

# Disable scientific notations from Pandas library methods
pd.set_option("display.float_format", "{:.2f}".format)

USvideos = pd.read_csv("../datasets/USvideos.csv")

### **2. Quick Overview**

Get the conscise summary of the dataset's structure and descriptive statistics of the dataset using `info()` and `describe()` method respectively.

In [64]:
print("Dataset overview:")
display(USvideos.info())

Dataset overview:
<class 'pandas.DataFrame'>
RangeIndex: 40949 entries, 0 to 40948
Data columns (total 16 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   video_id                40949 non-null  str
 1   trending_date           40949 non-null  str
 2   title                   40949 non-null  str
 3   channel_title           40949 non-null  str
 4   category_id             40949 non-null  int64
 5   publish_time            40949 non-null  str
 6   tags                    40949 non-null  str
 7   views                   40949 non-null  int64
 8   likes                   40949 non-null  int64
 9   dislikes                40949 non-null  int64
 10  comment_count           40949 non-null  int64
 11  thumbnail_link          40949 non-null  str
 12  comments_disabled       40949 non-null  bool
 13  ratings_disabled        40949 non-null  bool
 14  video_error_or_removed  40949 non-null  bool
 15  description             40379 non-null  str
dtypes: bool(3), int64(5), str(8)
memory usage: 4.2 MB

None

In [65]:
display(USvideos[["views", "likes", "dislikes", "comment_count"]].describe())

             views      likes   dislikes  comment_count
count     40949.00   40949.00   40949.00       40949.00
mean    2360784.64   74266.70    3711.40        8446.80
std     7394113.76  228885.34   29029.71       37430.49
min         549.00       0.00       0.00           0.00
25%      242329.00    5424.00     202.00         614.00
50%      681861.00   18091.00     631.00        1856.00
75%     1823157.00   55417.00    1938.00        5755.00
max   225211923.00 5613827.00 1674420.00     1361580.00

Get the dataset shape using `shape` attribute.

In [66]:
display(f"The number of rows and columns: {USvideos.shape}")

'The number of rows and columns: (40949, 16)'

Check what columns or variables consist of **missing values** using `isnull()` and combine by `sum()` method to get the total number of values.

In [67]:
columns = USvideos.columns

for column in columns:
    no_of_missing_values = USvideos[column].isnull().sum()

    if no_of_missing_values > 0:
        display(f"Column: `{column}`")
        display(f"Number of missing values: {no_of_missing_values}")

'Column: `description`'

'Number of missing values: 570'

Check the number of unique values for all columns with non-numeric values.

In [68]:
columns = [
    "video_id",
    "trending_date",
    "title",
    "channel_title",
    "publish_time",
    "tags",
    "description"
]

for column in columns:
    no_of_unique_values = len(USvideos[column].dropna().unique())
    display(f"Number of unique values of the column `{column}`: {no_of_unique_values}")

'Number of unique values of the column `video_id`: 6351'

'Number of unique values of the column `trending_date`: 205'

'Number of unique values of the column `title`: 6455'

'Number of unique values of the column `channel_title`: 2207'

'Number of unique values of the column `publish_time`: 6269'

'Number of unique values of the column `tags`: 6055'

'Number of unique values of the column `description`: 6901'

Check the unique values of some columns.

In [69]:
for column in columns:
    unique_values = USvideos[column].dropna().unique()

    if column == "tags":
        unique_values = unique_values[:3]

    else:
        unique_values = unique_values[:5]
    
    display(f"Some unique values of column `{column}`:")
    display(unique_values)

'Some unique values of column `video_id`:'

<StringArray>
['2kyS6SvSYSE', '1ZAPwfrtAFY', '5qpjK5DgCt4', 'puqaWrEC7tY', 'd380meD0W0M']
Length: 5, dtype: str

'Some unique values of column `trending_date`:'

<StringArray>
['17.14.11', '17.15.11', '17.16.11', '17.17.11', '17.18.11']
Length: 5, dtype: str

'Some unique values of column `title`:'

<StringArray>
[                            'WE WANT TO TALK ABOUT OUR MARRIAGE',
 'The Trump Presidency: Last Week Tonight with John Oliver (HBO)',
          'Racist Superman | Rudy Mancuso, King Bach & Lele Pons',
                               'Nickelback Lyrics: Real or Fake?',
                                       'I Dare You: GOING BALD!?']
Length: 5, dtype: str

'Some unique values of column `channel_title`:'

<StringArray>
[         'CaseyNeistat',       'LastWeekTonight',          'Rudy Mancuso',
 'Good Mythical Morning',              'nigahiga']
Length: 5, dtype: str

'Some unique values of column `publish_time`:'

<StringArray>
['2017-11-13T17:13:01.000Z', '2017-11-13T07:30:00.000Z',
 '2017-11-12T19:05:24.000Z', '2017-11-13T11:00:04.000Z',
 '2017-11-12T18:01:41.000Z']
Length: 5, dtype: str

'Some unique values of column `tags`:'

<StringArray>
[                                                                                                                                                                                                                                                                                                           'SHANtell martin',
                                                                                                                                                                                                                     'last week tonight trump presidency|"last week tonight donald trump"|"john oliver trump"|"donald trump"',
 'racist superman|"rudy"|"mancuso"|"king"|"bach"|"racist"|"superman"|"love"|"rudy mancuso poo bear black white official music video"|"iphone x by pineapple"|"lelepons"|"hannahstocking"|"rudymancuso"|"inanna"|"anwar"|"sarkis"|"shots"|"shotsstudios"|"alesso"|"anitta"|"brazil"|"Getting My Driver's License | Lele Pons"']
Length: 3, dtype: str

'Some unique values of column `description`:'

<StringArray>
['SHANTELL'S CHANNEL - https://www.youtube.com/shantellmartin\nCANDICE - https://www.lovebilly.com\n\nfilmed this video in 4k on this -- http://amzn.to/2sTDnRZ\nwith this lens -- http://amzn.to/2rUJOmD\nbig drone - http://tinyurl.com/h4ft3oy\nOTHER GEAR ---  http://amzn.to/2o3GLX5\nSony CAMERA http://amzn.to/2nOBmnv\nOLD CAMERA; http://amzn.to/2o2cQBT\nMAIN LENS; http://amzn.to/2od5gBJ\nBIG SONY CAMERA; http://amzn.to/2nrdJRO\nBIG Canon CAMERA; http://tinyurl.com/jn4q4vz\nBENDY TRIPOD THING; http://tinyurl.com/gw3ylz2\nYOU NEED THIS FOR THE BENDY TRIPOD; http://tinyurl.com/j8mzzua\nWIDE LENS; http://tinyurl.com/jkfcm8t\nMORE EXPENSIVE WIDE LENS; http://tinyurl.com/zrdgtou\nSMALL CAMERA; http://tinyurl.com/hrrzhor\nMICROPHONE; http://tinyurl.com/zefm4jy\nOTHER MICROPHONE; http://tinyurl.com/jxgpj86\nOLD DRONE (cheaper but still great);http://tinyurl.com/zcfmnmd\n\nfollow me; on http://instagram.com/caseyneistat\non https://www.facebook.com/cneistat\non https://twitter.com/CaseyNeistat\n\namazing intro song by https://soundcloud.com/discoteeth\n\nad disclosure.  THIS IS NOT AN AD.  not selling or promoting anything.  but samsung did produce the Shantell Video as a 'GALAXY PROJECT' which is an initiative that enables creators like Shantell and me to make projects we might otherwise not have the opportunity to make.  hope that's clear.  if not ask in the comments and i'll answer any specifics.',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             'One year after the presidential election, John Oliver discusses what we've learned so far and enlists our catheter cowboy to teach Donald Trump what he hasn't.\n\nConnect with Last Week Tonight online...\n\nSubscribe to the Last Week Tonight YouTube channel for more almost news as it almost happens: www.youtube.com/user/LastWeekTonight\n\nFind Last Week Tonight on Facebook like your mom would: http://Facebook.com/LastWeekTonight\n\nFollow us on Twitter for news about jokes and jokes about news: http://Twitter.com/LastWeekTonight\n\nVisit our official site for all that other stuff at once: http://www.hbo.com/lastweektonight',
                                                                                                                                                                                                                                          'WATCH MY PREVIOUS VIDEO ▶ \n\nSUBSCRIBE ► https://www.youtube.com/channel/UC5jkXpfnBhlDjqh0ir5FsIQ?sub_confirmation=1\n\nTHANKS FOR WATCHING! LIKE & SUBSCRIBE FOR MORE VIDEOS!\n-----------------------------------------------------------\nFIND ME ON: \nInstagram | http://instagram.com/rudymancuso\nTwitter | http://twitter.com/rudymancuso\nFacebook | http://facebook.com/rudymancuso\n\nCAST: \nRudy Mancuso | http://youtube.com/c/rudymancuso\nLele Pons | http://youtube.com/c/lelepons\nKing Bach | https://youtube.com/user/BachelorsPadTv\n\nVideo Effects: \nCaleb Natale | https://instagram.com/calebnatale\n\nPA:\nPaulina Gregory\n\n\nShots Studios Channels:\nAlesso | https://youtube.com/c/alesso\nAnitta | http://youtube.com/c/anitta\nAnwar Jibawi | http://youtube.com/c/anwar\nAwkward Puppets | http://youtube.com/c/awkwardpuppets\nHannah Stocking | http://youtube.com/c/hannahstocking\nInanna Sarkis | http://youtube.com/c/inanna\nLele Pons | http://youtube.com/c/lelepons\nMaejor | http://youtube.com/c/maejor\nMike Tyson | http://youtube.com/c/miketyson \nRudy Mancuso | http://youtube.com/c/rudymancuso\nShots Studios | http://youtube.com/c/shots\n\n#Rudy\n#RudyMancuso',
        'Today we find out if Link is a Nickelback amateur or a secret Nickelback devotee. GMM #1218\nDon't miss an all new Ear Biscuits: https://goo.gl/xeZNQt\nWatch Part 4: https://youtu.be/MhCdiiB8CQg | Watch Part 2: https://youtu.be/7qiOrNao9fg\nWatch today's episode from the start: http://bit.ly/GMM1218\n\nPick up all of the official GMM merch only at https://mythical.store\n\nFollow Rhett & Link: \nInstagram: https://instagram.com/rhettandlink\nFacebook: https://facebook.com/rhettandlink\nTwitter: https://twitter.com/rhettandlink\nTumblr: https://rhettandlink.tumblr.com\nSnapchat: @realrhettlink\nWebsite: https://mythical.co/\n\nCheck Out Our Other Mythical Channels:\nGood Mythical MORE: https://youtube.com/goodmythicalmore\nRhett & Link: https://youtube.com/rhettandlink\nThis Is Mythical: https://youtube.com/thisismythical\nEar Biscuits: https://applepodcasts.com/earbiscuits\n\nWant to send us something? https://mythical.co/contact\nHave you made a Wheel of Mythicality intro video? Submit it here: https://bit.ly/GMMWheelIntro\n\nIntro Animation by Digital Twigs: https://www.digitaltwigs.com\nIntro & Outro Music by Jeff Zeigler & Sarah Schimeneck https://www.jeffzeigler.com\nWheel of Mythicality theme: https://www.royaltyfreemusiclibrary.com/\nAll Supplemental Music fromOpus 1 Music: https://opus1.sourceaudio.com/\nWe use ‘The Mouse’ by Blue Microphones https://www.bluemic.com/mouse/',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       'I know it's been a while since we did this show, but we're back with what might be the best episode yet!\nLeave your dares in the comment section! \n\nOrder my book how to write good \nhttp://higatv.com/ryan-higas-how-to-write-good-pre-order-links/\n\nJust Launched New Official Store\nhttps://www.gianthugs.com/collections/ryan\n\nHigaTV Channel\nhttp://www.youtube.com/higatv\n\nTwitter\nhttp://www.twitter.com/therealryanhiga\n\nFacebook\nhttp://www.facebook.com/higatv\n\nWebsite\nhttp://www.higatv.com\n\nInstagram\nhttp://www.instagram.com/notryanhiga\n\nSend us mail or whatever you want here!\nPO Box 232355\nLas Vegas, NV 89105']
Length: 5, dtype: str

Check the number of unique values for some columns.

### **3. Data Cleaning**

Now that we have the overview of what's inside the dataset such as the number of rows and columns, the number of missing values for all columns, unique values per column, and statistical description of the dataset. We will now proceed to clean the dataset based on what we've observed earlier on.

In [70]:
# Handle the missing values of the `description` column
USvideos["description"] = USvideos["description"].fillna("No description")

# Standardize the datatype of `trending_date` and `publish_time` columns
USvideos["trending_date"] = pd.to_datetime(USvideos["trending_date"], format="%y.%d.%m")
USvideos["publish_time"] = pd.to_datetime(USvideos["publish_time"], format="%Y-%m-%dT%H:%M:%S.%fZ")

# Remove unnecessary characters to the `tags` column
USvideos["tags"] = USvideos["tags"].str.replace("[none]", "No tags")
USvideos["tags"] = USvideos["tags"].str.replace("\"", "")
USvideos["tags"] = str(USvideos["tags"].str.split("|").str.join(", "))

# Remove duplicates of `video_id` column which is the unique identifier of the dataset
USvideos.drop_duplicates(subset=["video_id"], keep="last", inplace=True)

### **4. Data Analysis**

After performing **data cleaning**, we can now proceed to analyze and gain insights by performing data filtering using [**pandas.DataFrame.loc**](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.loc.html) and [**pandas.DataFrame.iloc**](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.iloc.html) to the dataset.

Get the row with the index label of `40944` from the dataset.

In [71]:
display(USvideos.loc[40944])

video_id                                                        BZt0qjTWNhw
trending_date                                           2018-06-14 00:00:00
title                                          The Cat Who Caught the Laser
channel_title                                                 AaronsAnimals
category_id                                                              15
publish_time                                            2018-05-18 13:00:04
tags                      0                                          SHA...
views                                                               1685609
likes                                                                 38160
dislikes                                                               1385
comment_count                                                          2657
thumbnail_link               https://i.ytimg.com/vi/BZt0qjTWNhw/default.jpg
comments_disabled                                                     False
ratings_disabled                                                      False
video_error_or_removed                                                False
description                  The Cat Who Caught the Laser - Aaron's Animals
Name: 40944, dtype: object

Get all rows starting from the index label `10` to `75` using index label slicing.

In [72]:
display(USvideos.loc[10:76])

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description
10,9wRQljFNDW8,2017-11-14,Dion Lewis' 103-Yd Kick Return TD vs. Denver! ...,NFL,17,2017-11-13 02:05:26,0 SHA...,81377,655,25,177,https://i.ytimg.com/vi/9wRQljFNDW8/default.jpg,False,False,False,New England Patriots returner Dion Lewis blast...
36,Om_zGhJLZ5U,2017-11-14,TL;DW - Every DCEU Movie Before Justice League,Screen Junkies,1,2017-11-12 18:00:03,0 SHA...,288922,7515,792,2111,https://i.ytimg.com/vi/Om_zGhJLZ5U/default.jpg,False,False,False,With Justice League approaching fast we rewatc...
41,goP4Z5wyOlM,2017-11-14,Iraq-Iran earthquake: Deadly tremor hits borde...,BBC News,25,2017-11-12 21:16:40,0 SHA...,34785,308,26,413,https://i.ytimg.com/vi/goP4Z5wyOlM/default.jpg,False,False,False,A strong 7.2-magnitude earthquake has rattled ...
55,8NHA23f7LvU,2017-11-14,Jason Momoa Wows Hugh Grant With Some Dothraki...,The Graham Norton Show,24,2017-11-10 19:06:23,0 SHA...,1496225,16116,236,605,https://i.ytimg.com/vi/8NHA23f7LvU/default.jpg,False,False,False,I think Sarah Millican was very excited for th...
76,IE-xepGLVt8,2017-11-14,Mayo Clinic's first face transplant patient me...,Mayo Clinic,28,2017-11-10 12:04:17,0 SHA...,237307,1896,74,260,https://i.ytimg.com/vi/IE-xepGLVt8/default.jpg,False,False,False,One and a half years after the surgery that tr...

Get all the rows with an index label of `40944`, `40945`, `40946`, and `40947`.

In [73]:
display(USvideos.loc[[40944, 40945, 40946, 40947]])

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description
40944,BZt0qjTWNhw,2018-06-14,The Cat Who Caught the Laser,AaronsAnimals,15,2018-05-18 13:00:04,0 SHA...,1685609,38160,1385,2657,https://i.ytimg.com/vi/BZt0qjTWNhw/default.jpg,False,False,False,The Cat Who Caught the Laser - Aaron's Animals
40945,1h7KV2sjUWY,2018-06-14,True Facts : Ant Mutualism,zefrank1,22,2018-05-18 01:00:06,0 SHA...,1064798,60008,382,3936,https://i.ytimg.com/vi/1h7KV2sjUWY/default.jpg,False,False,False,No description
40946,D6Oy4LfoqsU,2018-06-14,I GAVE SAFIYA NYGAARD A PERFECT HAIR MAKEOVER ...,Brad Mondo,24,2018-05-18 17:34:22,0 SHA...,1066451,48068,1032,3992,https://i.ytimg.com/vi/D6Oy4LfoqsU/default.jpg,False,False,False,I had so much fun transforming Safiyas hair in...
40947,oV0zkMe1K8s,2018-06-14,How Black Panther Should Have Ended,How It Should Have Ended,1,2018-05-17 17:00:04,0 SHA...,5660813,192957,2846,13088,https://i.ytimg.com/vi/oV0zkMe1K8s/default.jpg,False,False,False,How Black Panther Should Have EndedWatch More ...

Get all the rows with `views` greater than or equal to **1,000,000** views using boolean masking.

In [74]:
high_viewed_USvideos = USvideos.loc[USvideos["views"] >= 1000000]
display(high_viewed_USvideos)

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description
55,8NHA23f7LvU,2017-11-14,Jason Momoa Wows Hugh Grant With Some Dothraki...,The Graham Norton Show,24,2017-11-10 19:06:23,0 SHA...,1496225,16116,236,605,https://i.ytimg.com/vi/8NHA23f7LvU/default.jpg,False,False,False,I think Sarah Millican was very excited for th...
78,cOc3tsFWoRs,2017-11-14,Jason Momoa & Lisa Bonet: Love at First Sight,The Late Late Show with James Corden,24,2017-11-10 09:35:00,0 SHA...,1497519,15504,353,1084,https://i.ytimg.com/vi/cOc3tsFWoRs/default.jpg,False,False,False,James congratulates Jason Momoa on recently ma...
104,pz95u3UVpaM,2017-11-14,Camila Cabello - Havana (Vertical Video) ft. Y...,CamilaCabelloVEVO,10,2017-11-10 05:01:00,0 SHA...,5476737,286268,4083,12254,https://i.ytimg.com/vi/pz95u3UVpaM/default.jpg,False,False,False,Havana – Spotify Vertical Video \nVideo Direct...
117,dW4wpGg64pE,2017-11-14,Meryl Streep Meets Anna Wintour at Vogue,Vogue,24,2017-11-09 18:20:27,0 SHA...,1017803,25122,628,1504,https://i.ytimg.com/vi/dW4wpGg64pE/default.jpg,False,False,False,The pair had a frank and far-ranging conversat...
122,k29YnfttqEU,2017-11-14,Mean Tweets – Country Music Edition #3,Jimmy Kimmel Live,23,2017-11-09 04:58:04,0 SHA...,1315873,9312,584,769,https://i.ytimg.com/vi/k29YnfttqEU/default.jpg,False,False,False,"From time to time, we like to shine a light on..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40944,BZt0qjTWNhw,2018-06-14,The Cat Who Caught the Laser,AaronsAnimals,15,2018-05-18 13:00:04,0 SHA...,1685609,38160,1385,2657,https://i.ytimg.com/vi/BZt0qjTWNhw/default.jpg,False,False,False,The Cat Who Caught the Laser - Aaron's Animals
40945,1h7KV2sjUWY,2018-06-14,True Facts : Ant Mutualism,zefrank1,22,2018-05-18 01:00:06,0 SHA...,1064798,60008,382,3936,https://i.ytimg.com/vi/1h7KV2sjUWY/default.jpg,False,False,False,No description
40946,D6Oy4LfoqsU,2018-06-14,I GAVE SAFIYA NYGAARD A PERFECT HAIR MAKEOVER ...,Brad Mondo,24,2018-05-18 17:34:22,0 SHA...,1066451,48068,1032,3992,https://i.ytimg.com/vi/D6Oy4LfoqsU/default.jpg,False,False,False,I had so much fun transforming Safiyas hair in...
40947,oV0zkMe1K8s,2018-06-14,How Black Panther Should Have Ended,How It Should Have Ended,1,2018-05-17 17:00:04,0 SHA...,5660813,192957,2846,13088,https://i.ytimg.com/vi/oV0zkMe1K8s/default.jpg,False,False,False,How Black Panther Should Have EndedWatch More ...
40948,ooyjaVdt-jA,2018-06-14,Official Call of Duty®: Black Ops 4 — Multipla...,Call of Duty,20,2018-05-17 17:09:38,0 SHA...,10306119,357079,212976,144795,https://i.ytimg.com/vi/ooyjaVdt-jA/default.jpg,False,False,False,Call of Duty: Black Ops 4 Multiplayer raises t...

Get the **top 10 most viewed US YouTube Videos**.

In [75]:
# Sort the row based on highest to lowest views
highest_viewed_USvideos = high_viewed_USvideos.sort_values(by="views", ascending=False)
top_10_highest_viewed_USvideos = highest_viewed_USvideos[:10]

top_10_highest_viewed_USvideos.to_csv("../outputs/top_10_highest_viewed_USvideos.csv", index=False)
display(top_10_highest_viewed_USvideos)

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description
38547,VYOjWnS4cMY,2018-06-02,Childish Gambino - This Is America (Official V...,ChildishGambinoVEVO,10,2018-05-06 04:00:07,0 SHA...,225211923,5023450,343541,517232,https://i.ytimg.com/vi/VYOjWnS4cMY/default.jpg,False,False,False,“This is America” by Childish Gambino http://s...
6181,FlsCjmMhFmw,2017-12-14,YouTube Rewind: The Shape of 2017 | #YouTubeRe...,YouTube Spotlight,24,2017-12-06 17:58:51,0 SHA...,149376127,3093544,1643059,810698,https://i.ytimg.com/vi/FlsCjmMhFmw/default.jpg,False,False,False,"YouTube Rewind 2017. Celebrating the videos, p..."
34708,ffxKSjUwKdU,2018-05-14,Ariana Grande - No Tears Left To Cry,ArianaGrandeVevo,10,2018-04-20 04:00:03,0 SHA...,148689896,3094021,129502,242039,https://i.ytimg.com/vi/ffxKSjUwKdU/default.jpg,False,False,False,No Tears Left To Cry (Official Video)Song Avai...
34888,zEf423kYfqk,2018-05-15,"Becky G, Natti Natasha - Sin Pijama (Official ...",BeckyGVEVO,10,2018-04-20 10:40:51,0 SHA...,139334502,1425496,119798,83941,https://i.ytimg.com/vi/zEf423kYfqk/default.jpg,False,False,False,Becky G & Natti Natasha – “Sin Pijama”NUEVO SE...
38273,7C2z4GqqS5E,2018-06-01,BTS (방탄소년단) 'FAKE LOVE' Official MV,ibighit,10,2018-05-18 09:00:02,0 SHA...,123010920,5613827,206892,1228655,https://i.ytimg.com/vi/7C2z4GqqS5E/default.jpg,False,False,False,BTS (방탄소년단) 'FAKE LOVE' Official MVDirector : ...
34747,M4ZoCHID9GI,2018-05-14,The Weeknd - Call Out My Name (Official Video),TheWeekndVEVO,10,2018-04-12 16:00:04,0 SHA...,122544931,1427436,40837,55320,https://i.ytimg.com/vi/M4ZoCHID9GI/default.jpg,False,False,False,Call Out My Name (Official Video)Taken from th...
2587,TyHvyGVs42U,2017-11-26,"Luis Fonsi, Demi Lovato - Échame La Culpa",LuisFonsiVEVO,10,2017-11-17 05:00:01,0 SHA...,102012605,2376636,117196,134224,https://i.ytimg.com/vi/TyHvyGVs42U/default.jpg,False,False,False,“Échame La Culpa” disponible ya en todas las p...
40869,xTlNMmZKwpA,2018-06-14,"Cardi B, Bad Bunny & J Balvin - I Like It [Off...",Cardi B,10,2018-05-29 14:05:10,0 SHA...,94254507,1816753,102474,101077,https://i.ytimg.com/vi/xTlNMmZKwpA/default.jpg,False,False,False,"Cardi B, Bad Bunny & J Balvin - I Like It from..."
4997,6ZfuNTqbHE8,2017-12-08,Marvel Studios' Avengers: Infinity War Officia...,Marvel Entertainment,24,2017-11-29 13:26:24,0 SHA...,91933007,2625661,53709,350458,https://i.ytimg.com/vi/6ZfuNTqbHE8/default.jpg,False,False,False,There was an idea… Avengers: Infinity War. In ...
25947,-BQJo3vK8O8,2018-03-25,Maluma - El Préstamo (Official Video),MalumaVEVO,10,2018-03-09 11:00:01,0 SHA...,87264467,815369,71494,35945,https://i.ytimg.com/vi/-BQJo3vK8O8/default.jpg,False,False,False,Maluma - El Prestamo (Official Music Video)\nE...

Save the **top 10 most viewed US YouTube Videos** to a separated csv file.

In [76]:
top_10_highest_viewed_USvideos.to_csv("../outputs/top_10_highest_viewed_USvideos.csv", index=False)

Get the row with the index label of `2383` and extract only the value of the `title` column

In [77]:
display(USvideos.loc[2383, "title"])

"Chris Stapleton - Tryin' To Untangle My Mind (Audio)"

Get a group of rows starting from the index label `15500` to `15600` (inclusive) using index label slicing and extract only the values of the `description` column.

In [78]:
display(USvideos.loc[15500:15600, "description"])

15514    Programme website: http://bbc.in/2FkwhuK Tom C...
15523    HAIM SISTER SISTER SISTER Tour on sale now: ht...
15525    For You (Fifty Shades Freed) (Official Video)\...
15527    $14,000 GOLD bar cut in half with a waterjet. ...
15528    The first eliminated queen packs up her drag s...
                               ...
15589    The repeal of Net Neutrality is a hot topic in...
15590    David Schwimmer is stuck in an unhealthy relat...
15591    Please SUBSCRIBE - http://bit.ly/BWchannel\nTo...
15592    My Diamond Glow Powders http://bit.ly/2CJWrXw\...
15593    In her first TV interview since leaving the Wh...
Name: description, Length: 67, dtype: str

Get all the rows with an index label of `23742`, `4772`, `33689` and extract only the values of `channel_title` column.

In [79]:
display(USvideos.loc[[23742, 4772, 33689], "channel_title"])

23742    The Joint Forces Channel
4772                   Mark Rober
33689                   FORMULA 1
Name: channel_title, dtype: str

Get all the rows of the dataset that the year from `publish_time` column starts from **2018** and up.

In [80]:
display(USvideos.loc[USvideos["publish_time"].dt.year >= 2018, "channel_title"])

10006                               Netflix
10009                          TheEllenShow
10028                                   NFL
10029                            Refinery29
10206    The Late Show with Stephen Colbert
                        ...
40944                         AaronsAnimals
40945                              zefrank1
40946                            Brad Mondo
40947              How It Should Have Ended
40948                          Call of Duty
Name: channel_title, Length: 4128, dtype: str

Get the row with an index label of `5988` and extract the values from the specified columns: `channel_title`, `title`, `publish_time`, `views`, `likes`, `dislikes`, and `comment_count`.

In [81]:
display(USvideos.loc[5988, ["channel_title", "title", "publish_time", "views", "likes", "dislikes", "comment_count"]])

channel_title                              Just Marcus
title            REACTING TO ME IN YOUTUBE REWIND 2017
publish_time                       2017-12-08 13:04:18
views                                            46706
likes                                             3091
dislikes                                            47
comment_count                                      130
Name: 5988, dtype: object